services:
  vault-system:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8545:8545"
    environment:
      - PRIVATE_KEY=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80